name: Scipio ERP Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Install Apache Ant
      run: choco install ant -y

    - name: Verify Installation
      run: |
        java -version
        ant -version

    - name: Build and Install (Development Mode)
      run: ant build load-demo

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: scipio-erp-build
        path: target/*.jar

    - name: Cleanup
      run: echo "Installation completed successfully"
