name: Scipio ERP Build

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run install.bat
        shell: cmd
        run: echo 1 | install.bat

      - name: Verify installation
        run: echo "Installation completed successfully"
