name: Scipio ERP Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: ant build

    - name: Option Selection
      id: option-selection
      run: |
        echo "Select build option:"
        echo "1. Install for development"
        echo "2. Install for production"
        echo "3. Recompile"
        echo "4. List compiler information"
        set /p input="Enter a number (1-4): "
        if "%input%" == "1" (
          echo Running development install...
          ant build load-demo
        ) else if "%input%" == "2" (
          echo Running production install...
          ant build load-extseed create-admin-user-login
        ) else if "%input%" == "3" (
          echo Recompiling project...
          ant build
        ) else if "%input%" == "4" (
          echo Listing compiler information...
          ant -p
        ) else (
          echo Invalid option. Please select a valid number.
          exit 1
        )

    - name: Upload build artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: scipio-erp-build
        path: target/*.jar

    - name: Clean up
      run: echo "Build process complete."

  quit:
    runs-on: self-hosted
    needs: build
    if: failure()
    steps:
    - name: Thank You Message
      run: |
        echo "==============THANK YOU=============="
        echo "To start the application, type:"
        echo "Linux: ./start.sh"
        echo "OS X: bash ./start.sh"
        echo "Windows: start.bat"
        echo "Press any key to continue."
